# What is NumPy?
Numpy facilitates efficient numerical operations on large quantities of data. It is designed for efficiency on large datasets.
1. NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects.
2. Numpy can operate on this memory without any type checking or other overhead.
3. NumPy arrays also use much less memory than built-in Python sequences.
4. Allows you to perform complex calculations on entire array without using for loops.
5. **Vectorization**: Any arithmetic operations between equal-size NumPy arrays apply the operation element-wise

# `ndarray`: Multidimensional Array Object
N-dimensional array object, or ndarray, is a fast, flexible container for large datasets in Python. It stores **homogeneous data**, i.e. data type of all elements should be the same.
1. `np_array.shape` will provide the shape (rows, columns) of the array as a tuple
2. `np_array.dtype` will shpw the dat type of the array
3. `np_array.data` will show the memory location of the array
4. `np_array.ndim` will show number of dimensions

# Creating `ndarrays`

In [20]:
import numpy as np
# Use the array() function
# One-Dimensional array
data1 = np.array([1,2,3,4,5,6])
# Two-Dimensional array
data2 = np.array([[1,2,3,4], [5,6,7,8]])

# Create an array of 0's
print('2D array of zeros')
print(np.zeros((3,6)))
print('1D array of zeros')
print(np.zeros(10))

# Creating an array with random values
print('2D array of random values')
print(np.random.random((2,2)))

# Fill a 2D array with value of 7
print('Fill a 2D array with value of 7')
print(np.full((2,2),7))

# Array with evenly spaced values
print('Array with evenly spaced values')
print(np.arange(10,25,5))

# Another array with evenly spaced values
print('Another Array with evenly spaced values')
print(np.linspace(0,2,9))

2D array of zeros
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
1D array of zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D array of random values
[[0.69537765 0.72390965]
 [0.64050078 0.44416228]]
Fill a 2D array with value of 7
[[7 7]
 [7 7]]
Array with evenly spaced values
[10 15 20]
Another Array with evenly spaced values
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# Casting Types
Use the `np_array.astype(np.dtype)` method to change dtypes, where `dtype` can be `float64, int32, string_` etc.
If casting fails, it would raise a `ValueError`

In [26]:
arr = np.array([1,2,3,4])
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

In [27]:
np.arange(4)

array([0, 1, 2, 3])