In [1]:
import numpy as np

In [27]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
y = [True,False,True]

In [36]:
x.shape

(3, 4)

In [38]:
z=x[y]
z

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [40]:
a = [False,True,True,False]
b = x[:,a]
b

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])